// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency

import (
	"context"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/sriganeshlokesh/keysmith/adapter/repository/postgres"
	http2 "github.com/sriganeshlokesh/keysmith/api/http"
	"github.com/sriganeshlokesh/keysmith/api/http/handle"
	"github.com/sriganeshlokesh/keysmith/config"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

// InitializeServer is the wire injector that builds the complete *http.Server.
// The returned cleanup closes the database pool.
// wire.Build is replaced by generated code in wire_gen.go.
func InitializeServer(ctx context.Context, cfg *config.Config, logger *slog.Logger) (*http.Server, func(), error) {
	pool, cleanup, err := postgres.NewPool(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	healthHandler := handle.NewHealthHandler(cfg, pool)
	handler := http2.NewRouter(cfg, logger, healthHandler)
	server := http2.NewServer(cfg, handler, logger)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

// ServerSet groups the providers needed to build an *http.Server.
// Consumer-declared interfaces are bound to their implementations here.
var ServerSet = wire.NewSet(postgres.NewPool, handle.NewHealthHandler, http2.NewRouter, http2.NewServer, wire.Bind(new(handle.DBPinger), new(*pgxpool.Pool)), wire.Bind(new(http2.HealthRoutes), new(*handle.HealthHandler)))
