// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency

import (
	"context"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/sriganeshlokesh/keysmith/adapter/job"
	"github.com/sriganeshlokesh/keysmith/adapter/repository/postgres"
	"github.com/sriganeshlokesh/keysmith/api/http"
	"github.com/sriganeshlokesh/keysmith/api/http/handle"
	"github.com/sriganeshlokesh/keysmith/api/http/middleware"
	"github.com/sriganeshlokesh/keysmith/application/oauth"
	"github.com/sriganeshlokesh/keysmith/application/password"
	"github.com/sriganeshlokesh/keysmith/application/token"
	"github.com/sriganeshlokesh/keysmith/config"
	"github.com/sriganeshlokesh/keysmith/domain/repo"
	"github.com/sriganeshlokesh/keysmith/domain/service"
	"log/slog"
)

// Injectors from wire.go:

// InitializeApp is the wire injector that builds the complete App.
// The returned cleanup closes the database pool.
// wire.Build is replaced by generated code in wire_gen.go.
func InitializeApp(ctx context.Context, cfg *config.Config, logger *slog.Logger) (*App, func(), error) {
	pool, cleanup, err := postgres.NewPool(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	healthHandler := handle.NewHealthHandler(cfg, pool)
	signer, err := ProvideSigner(cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jwksHandler := handle.NewJWKSHandler(signer)
	userRepo := postgres.NewUserRepo(pool)
	credentialRepo := postgres.NewCredentialRepo(pool)
	oneTimeTokenRepo := postgres.NewOneTimeTokenRepo(pool)
	refreshTokenRepo := postgres.NewRefreshTokenRepo(pool)
	emailSender, err := ProvideEmailSender(cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	passwordConfig := ProvidePasswordConfig(cfg)
	service, err := password.NewService(userRepo, credentialRepo, oneTimeTokenRepo, refreshTokenRepo, emailSender, passwordConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenConfig := ProvideTokenConfig(cfg)
	tokenService := token.NewService(signer, userRepo, refreshTokenRepo, tokenConfig, logger)
	passwordHandler := handle.NewPasswordHandler(cfg, service, tokenService)
	sessionHandler := handle.NewSessionHandler(cfg, tokenService)
	meHandler := handle.NewMeHandler(userRepo)
	v, err := ProvideOAuthProviders(ctx, cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	identityRepo := postgres.NewIdentityRepo(pool)
	oauthService := oauth.NewService(v, userRepo, identityRepo, logger)
	oAuthHandler := handle.NewOAuthHandler(cfg, oauthService, tokenService, logger)
	handler := http.NewRouter(cfg, logger, healthHandler, jwksHandler, passwordHandler, sessionHandler, meHandler, oAuthHandler, signer)
	server := http.NewServer(cfg, handler, logger)
	cleaner := token.NewCleaner(refreshTokenRepo, oneTimeTokenRepo, logger)
	jobCleanup := job.NewCleanup(cleaner, logger)
	app := NewApp(server, jobCleanup)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// AppSet groups the providers needed to build the App.
// Consumer-declared interfaces are bound to their implementations here.
var AppSet = wire.NewSet(postgres.NewPool, postgres.NewUserRepo, postgres.NewIdentityRepo, postgres.NewCredentialRepo, postgres.NewRefreshTokenRepo, postgres.NewOneTimeTokenRepo, ProvideSigner,
	ProvideTokenConfig,
	ProvidePasswordConfig,
	ProvideEmailSender,
	ProvideOAuthProviders, token.NewService, token.NewCleaner, password.NewService, oauth.NewService, job.NewCleanup, handle.NewHealthHandler, handle.NewJWKSHandler, handle.NewPasswordHandler, handle.NewSessionHandler, handle.NewMeHandler, handle.NewOAuthHandler, http.NewRouter, http.NewServer, NewApp, wire.Bind(new(handle.DBPinger), new(*pgxpool.Pool)), wire.Bind(new(handle.JWKSProvider), new(*service.Signer)), wire.Bind(new(handle.PasswordService), new(*password.Service)), wire.Bind(new(handle.SessionIssuer), new(*token.Service)), wire.Bind(new(handle.SessionService), new(*token.Service)), wire.Bind(new(handle.OAuthService), new(*oauth.Service)), wire.Bind(new(handle.UserGetter), new(*postgres.UserRepo)), wire.Bind(new(middleware.TokenVerifier), new(*service.Signer)), wire.Bind(new(http.HealthRoutes), new(*handle.HealthHandler)), wire.Bind(new(http.JWKSRoutes), new(*handle.JWKSHandler)), wire.Bind(new(http.PasswordRoutes), new(*handle.PasswordHandler)), wire.Bind(new(http.SessionRoutes), new(*handle.SessionHandler)), wire.Bind(new(http.MeRoutes), new(*handle.MeHandler)), wire.Bind(new(http.OAuthRoutes), new(*handle.OAuthHandler)), wire.Bind(new(repo.Users), new(*postgres.UserRepo)), wire.Bind(new(repo.Identities), new(*postgres.IdentityRepo)), wire.Bind(new(repo.PasswordCredentials), new(*postgres.CredentialRepo)), wire.Bind(new(repo.RefreshTokens), new(*postgres.RefreshTokenRepo)), wire.Bind(new(repo.OneTimeTokens), new(*postgres.OneTimeTokenRepo)), wire.Bind(new(job.Runner), new(*token.Cleaner)),
)
