// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency

import (
	"context"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/sriganeshlokesh/keysmith/adapter/job"
	"github.com/sriganeshlokesh/keysmith/adapter/repository/postgres"
	"github.com/sriganeshlokesh/keysmith/api/http"
	"github.com/sriganeshlokesh/keysmith/api/http/handle"
	"github.com/sriganeshlokesh/keysmith/application/token"
	"github.com/sriganeshlokesh/keysmith/config"
	"github.com/sriganeshlokesh/keysmith/domain/repo"
	"github.com/sriganeshlokesh/keysmith/domain/service"
	"log/slog"
)

// Injectors from wire.go:

// InitializeApp is the wire injector that builds the complete App.
// The returned cleanup closes the database pool.
// wire.Build is replaced by generated code in wire_gen.go.
func InitializeApp(ctx context.Context, cfg *config.Config, logger *slog.Logger) (*App, func(), error) {
	pool, cleanup, err := postgres.NewPool(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	healthHandler := handle.NewHealthHandler(cfg, pool)
	signer, err := ProvideSigner(cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jwksHandler := handle.NewJWKSHandler(signer)
	handler := http.NewRouter(cfg, logger, healthHandler, jwksHandler)
	server := http.NewServer(cfg, handler, logger)
	refreshTokenRepo := postgres.NewRefreshTokenRepo(pool)
	oneTimeTokenRepo := postgres.NewOneTimeTokenRepo(pool)
	cleaner := token.NewCleaner(refreshTokenRepo, oneTimeTokenRepo, logger)
	jobCleanup := job.NewCleanup(cleaner, logger)
	app := NewApp(server, jobCleanup)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// AppSet groups the providers needed to build the App.
// Consumer-declared interfaces are bound to their implementations here.
var AppSet = wire.NewSet(postgres.NewPool, postgres.NewRefreshTokenRepo, postgres.NewOneTimeTokenRepo, ProvideSigner, token.NewCleaner, job.NewCleanup, handle.NewHealthHandler, handle.NewJWKSHandler, http.NewRouter, http.NewServer, NewApp, wire.Bind(new(handle.DBPinger), new(*pgxpool.Pool)), wire.Bind(new(handle.JWKSProvider), new(*service.Signer)), wire.Bind(new(http.HealthRoutes), new(*handle.HealthHandler)), wire.Bind(new(http.JWKSRoutes), new(*handle.JWKSHandler)), wire.Bind(new(repo.RefreshTokens), new(*postgres.RefreshTokenRepo)), wire.Bind(new(repo.OneTimeTokens), new(*postgres.OneTimeTokenRepo)), wire.Bind(new(job.Runner), new(*token.Cleaner)))
